# -*- coding: utf-8 -*-
"""lab 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D-9yOWImW7b3ClBMFee58v4nr_lN_NPy
"""

print("Name: Mahnoor")
print("ID: 9938")
print("\nPython Version:")
print(sys.version)
print("\nWhat Programming for AI means to me:")
print("Programming for AI helps me turn ideas into intelligent solutions.")
print("It allows machines to learn from data and make smart decisions.")
print("I see it as the foundation of future technology and innovation.")