# -*- coding: utf-8 -*-
""Assignment no 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tErgbEpB-4Bj77BCeC5W78yX2jselK52

Task no # 1
"""

rent = 25000
food = 15000
transport = 8000
utilities = 10000
budget_limit = 60000
total_expense = rent + food + transport + utilities

print("Total Monthly Expense:", total_expense, "PKR")

if total_expense <= budget_limit:
    print("Status: Within Budget")
else:
    print("Status: Over Budget")

"""Task_no #02"""

units = int(input("Enter number of electricity units consumed: "))

if units <= 100:
    print("Billing Category: Basic Rate")
elif units <= 300:
    print("Billing Category: Standard Rate")
else:
    print("Billing Category: High Usage Rate")

"""Task no #03"""

attendance = [72, 85, 90, 60, 40, 78, 88]

meet_requirement = 0
not_meet_requirement = 0

for percentage in attendance:
    if percentage >= 75:
        meet_requirement += 1
    else:
        not_meet_requirement += 1

print("Students meeting attendance requirement:", meet_requirement)
print("Students not meeting attendance requirement:", not_meet_requirement)

"""Task_no #4"""

cgpas = [3.6, 3.3, 2.9, 3.4, 3.9, 3.0, 3.7]
incomes = [75000, 92000, 40000, 85000, 70000, 50000, 80000]

eligible_students = 0

for i in range(len(cgpas)):
    if cgpas[i] >= 3.5 and incomes[i] <= 80000:
        eligible_students += 1

print("Total number of eligible students:", eligible_students)

"""Task_no#05"""

readings = [15, 22, 35, 90, 50, 18, 75, 82, 60]

alert_count = 0

for value in readings:
    if value < 20 or value > 80:
        alert_count += 1

total_readings = len(readings)
alert_percentage = (alert_count / total_readings) * 100

print("Total Alerts:", alert_count)
print("Alert Percentage:", alert_percentage, "%")